disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Mason Speck"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = ""
description = "Mason Speck's portfolio and blog"

[author]
name = "Mason Speck"
headline = "Software Engineer"
links = [ 
    { github = "github.com/StopwatchString" },
     { linkedin = "https://www.linkedin.com/in/mason-speck-962b3b1a7" }
]
